[2023-04-25T12:34:35.659+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.extract_user manual__2023-04-25T12:34:34.652898+00:00 [queued]>
[2023-04-25T12:34:35.667+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.extract_user manual__2023-04-25T12:34:34.652898+00:00 [queued]>
[2023-04-25T12:34:35.668+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T12:34:35.668+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-04-25T12:34:35.669+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T12:34:35.681+0000] {taskinstance.py:1383} INFO - Executing <Task(SimpleHttpOperator): extract_user> on 2023-04-25 12:34:34.652898+00:00
[2023-04-25T12:34:35.687+0000] {standard_task_runner.py:55} INFO - Started process 11124 to run task
[2023-04-25T12:34:35.701+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'extract_user', 'manual__2023-04-25T12:34:34.652898+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp90azza57']
[2023-04-25T12:34:35.703+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask extract_user
[2023-04-25T12:34:35.779+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.extract_user manual__2023-04-25T12:34:34.652898+00:00 [running]> on host bebb68623a17
[2023-04-25T12:34:35.858+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=extract_user
AIRFLOW_CTX_EXECUTION_DATE=2023-04-25T12:34:34.652898+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-25T12:34:34.652898+00:00
[2023-04-25T12:34:35.859+0000] {http.py:121} INFO - Calling HTTP method
[2023-04-25T12:34:35.880+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-04-25T12:34:35.887+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-04-25T12:34:36.275+0000] {http.py:125} INFO - {"results":[{"gender":"female","name":{"title":"Mrs","first":"Milka","last":"Todorović"},"location":{"street":{"number":4010,"name":"Mitra Vasića"},"city":"Bujanovac","state":"Pomoravlje","country":"Serbia","postcode":99814,"coordinates":{"latitude":"62.0809","longitude":"75.0191"},"timezone":{"offset":"-1:00","description":"Azores, Cape Verde Islands"}},"email":"milka.todorovic@example.com","login":{"uuid":"9da66829-fe21-4643-9dfe-3e3c2853601f","username":"whiteduck911","password":"vauxhall","salt":"6lfzsog2","md5":"74bd54b0fdc9d74bad62cb6c0c9907d7","sha1":"6cce8edcd3f0fe5e34fbd7c09dcde7de35245924","sha256":"33a9450aa870ccc30058216a27f1f3dcbc9853bfc2bfd242727844426d7325b6"},"dob":{"date":"1956-10-07T10:43:57.583Z","age":66},"registered":{"date":"2018-06-03T21:31:08.519Z","age":4},"phone":"023-2300-906","cell":"063-2001-791","id":{"name":"SID","value":"351030715"},"picture":{"large":"https://randomuser.me/api/portraits/women/14.jpg","medium":"https://randomuser.me/api/portraits/med/women/14.jpg","thumbnail":"https://randomuser.me/api/portraits/thumb/women/14.jpg"},"nat":"RS"}],"info":{"seed":"eb4c6f4ec61f874e","results":1,"page":1,"version":"1.4"}}
[2023-04-25T12:34:36.276+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 132, in execute
    return self.response_filter(response, **kwargs)
  File "/opt/airflow/dags/user_processing.py", line 36, in <lambda>
    response_filter=lambda response: json.loads(response),
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not Response
[2023-04-25T12:34:36.287+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=extract_user, execution_date=20230425T123434, start_date=20230425T123435, end_date=20230425T123436
[2023-04-25T12:34:36.296+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 18 for task extract_user (the JSON object must be str, bytes or bytearray, not Response; 11124)
[2023-04-25T12:34:36.344+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-04-25T12:34:36.358+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
