[2023-04-26T05:53:50.951+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.insert_user manual__2023-04-26T05:53:44.298934+00:00 [queued]>
[2023-04-26T05:53:50.958+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.insert_user manual__2023-04-26T05:53:44.298934+00:00 [queued]>
[2023-04-26T05:53:50.959+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T05:53:50.960+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-04-26T05:53:50.960+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T05:53:50.968+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_user> on 2023-04-26 05:53:44.298934+00:00
[2023-04-26T05:53:50.975+0000] {standard_task_runner.py:55} INFO - Started process 225 to run task
[2023-04-26T05:53:50.979+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'insert_user', 'manual__2023-04-26T05:53:44.298934+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmplj54vnb5']
[2023-04-26T05:53:50.981+0000] {standard_task_runner.py:83} INFO - Job 173: Subtask insert_user
[2023-04-26T05:53:51.047+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.insert_user manual__2023-04-26T05:53:44.298934+00:00 [running]> on host b0d118a97f46
[2023-04-26T05:53:51.096+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=insert_user
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T05:53:44.298934+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T05:53:44.298934+00:00
[2023-04-26T05:53:51.106+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-04-26T05:53:51.111+0000] {sql.py:315} INFO - Running statement: 
            COPY users(first_name, last_name, country, username, password, email)
            FROM '/tmp/processed_user.csv'
            WITH (FORMAT CSV, HEADER FALSE);
        , parameters: None
[2023-04-26T05:53:51.113+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/tmp/processed_user.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2023-04-26T05:53:51.122+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=insert_user, execution_date=20230426T055344, start_date=20230426T055350, end_date=20230426T055351
[2023-04-26T05:53:51.130+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 173 for task insert_user (could not open file "/tmp/processed_user.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 225)
[2023-04-26T05:53:51.151+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-04-26T05:53:51.168+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
